//! gRPC service code generated by `tonic-build` from `proto/inference.proto`
//! at compile time.
//!
//! Re-exports the generated request/response messages and the
//! `InferenceService` server/client traits. Build a server by implementing
//! [`inference_service_server::InferenceService`] and serving
//! [`inference_service_server::InferenceServiceServer::new(impl_)`] under
//! `tonic::transport::Server`. The bundled `examples/server.rs` shows the
//! minimal wiring; production deployments will want to add their own TLS,
//! interceptors, and observability layers on top.

#![allow(missing_docs)]
#![allow(clippy::all)]

tonic::include_proto!("weirwood.inference.v1");
